
/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import { pgTable, index, uniqueIndex, foreignKey, integer, varchar, timestamp, serial, numeric, boolean, text, jsonb, pgEnum } from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'editor'])
export const enum_testimonials_source = pgEnum('enum_testimonials_source', ['google', 'facebook', 'instagram', 'email', 'in-person', 'other'])
export const enum_realizations_blocks_gallery_layout = pgEnum('enum_realizations_blocks_gallery_layout', ['grid', 'carousel', 'masonry'])
export const enum_realizations_category = pgEnum('enum_realizations_category', ['haircut', 'beard', 'combo', 'styling', 'other'])
export const enum_site_settings_social_platform = pgEnum('enum_site_settings_social_platform', ['instagram', 'facebook', 'tiktok', 'youtube', 'x', 'linkedin'])

export const users_sessions = pgTable('users_sessions', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}),
  expiresAt: timestamp('expires_at', {mode: 'string',withTimezone: true,precision: 3}).notNull(),
}, (columns) => [
    index('users_sessions_order_idx').on(columns._order), index('users_sessions_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: varchar('name').notNull(),
  role: enum_users_role('role').notNull().default("editor"),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  email: varchar('email').notNull(),
  resetPasswordToken: varchar('reset_password_token'),
  resetPasswordExpiration: timestamp('reset_password_expiration', {mode: 'string',withTimezone: true,precision: 3}),
  salt: varchar('salt'),
  hash: varchar('hash'),
  loginAttempts: numeric('login_attempts', {mode: 'number'}).default(0),
  lockUntil: timestamp('lock_until', {mode: 'string',withTimezone: true,precision: 3}),
}, (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt), index('users_created_at_idx').on(columns.createdAt), uniqueIndex('users_email_idx').on(columns.email),
]
)


export const media = pgTable('media', {
  id: serial('id').primaryKey(),
  alt: varchar('alt').notNull(),
  caption: varchar('caption'),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  url: varchar('url'),
  thumbnailURL: varchar('thumbnail_u_r_l'),
  filename: varchar('filename'),
  mimeType: varchar('mime_type'),
  filesize: numeric('filesize', {mode: 'number'}),
  width: numeric('width', {mode: 'number'}),
  height: numeric('height', {mode: 'number'}),
  focalX: numeric('focal_x', {mode: 'number'}),
  focalY: numeric('focal_y', {mode: 'number'}),
  sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
  sizes_thumbnail_width: numeric('sizes_thumbnail_width', {mode: 'number'}),
  sizes_thumbnail_height: numeric('sizes_thumbnail_height', {mode: 'number'}),
  sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
  sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', {mode: 'number'}),
  sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
  sizes_card_url: varchar('sizes_card_url'),
  sizes_card_width: numeric('sizes_card_width', {mode: 'number'}),
  sizes_card_height: numeric('sizes_card_height', {mode: 'number'}),
  sizes_card_mimeType: varchar('sizes_card_mime_type'),
  sizes_card_filesize: numeric('sizes_card_filesize', {mode: 'number'}),
  sizes_card_filename: varchar('sizes_card_filename'),
  sizes_hero_url: varchar('sizes_hero_url'),
  sizes_hero_width: numeric('sizes_hero_width', {mode: 'number'}),
  sizes_hero_height: numeric('sizes_hero_height', {mode: 'number'}),
  sizes_hero_mimeType: varchar('sizes_hero_mime_type'),
  sizes_hero_filesize: numeric('sizes_hero_filesize', {mode: 'number'}),
  sizes_hero_filename: varchar('sizes_hero_filename'),
}, (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt), index('media_created_at_idx').on(columns.createdAt), uniqueIndex('media_filename_idx').on(columns.filename), index('media_sizes_thumbnail_sizes_thumbnail_filename_idx').on(columns.sizes_thumbnail_filename), index('media_sizes_card_sizes_card_filename_idx').on(columns.sizes_card_filename), index('media_sizes_hero_sizes_hero_filename_idx').on(columns.sizes_hero_filename),
]
)


export const services = pgTable('services', {
  id: serial('id').primaryKey(),
  title: varchar('title').notNull(),
  slug: varchar('slug').notNull(),
  shortDescription: varchar('short_description').notNull(),
  priceLabel: varchar('price_label').notNull(),
  durationLabel: varchar('duration_label').notNull(),
  image: integer('image_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  order: numeric('order', {mode: 'number'}).default(0),
  isPopular: boolean('is_popular').default(false),
  isActive: boolean('is_active').default(true),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    uniqueIndex('services_slug_idx').on(columns.slug), index('services_image_idx').on(columns.image), index('services_updated_at_idx').on(columns.updatedAt), index('services_created_at_idx').on(columns.createdAt),
]
)


export const testimonials = pgTable('testimonials', {
  id: serial('id').primaryKey(),
  content: varchar('content').notNull(),
  authorName: varchar('author_name').notNull(),
  authorRole: varchar('author_role'),
  authorAvatar: integer('author_avatar_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  rating: numeric('rating', {mode: 'number'}).notNull().default(5),
  source: enum_testimonials_source('source').notNull().default("google"),
  order: numeric('order', {mode: 'number'}).default(0),
  isActive: boolean('is_active').default(true),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('testimonials_author_avatar_idx').on(columns.authorAvatar), index('testimonials_updated_at_idx').on(columns.updatedAt), index('testimonials_created_at_idx').on(columns.createdAt),
]
)


export const realizations_gallery = pgTable('realizations_gallery', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  image: integer('image_id').notNull().references(() => media.id, {
      onDelete: 'set null'
  }),
}, (columns) => [
    index('realizations_gallery_order_idx').on(columns._order), index('realizations_gallery_parent_id_idx').on(columns._parentID), index('realizations_gallery_image_idx').on(columns.image), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [realizations.id],
      name: 'realizations_gallery_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const realizations_blocks_paragraph = pgTable('realizations_blocks_paragraph', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  _path: text('_path').notNull(),
  id: varchar('id').primaryKey(),
  content: jsonb('content').notNull(),
  blockName: varchar('block_name'),
}, (columns) => [
    index('realizations_blocks_paragraph_order_idx').on(columns._order), index('realizations_blocks_paragraph_parent_id_idx').on(columns._parentID), index('realizations_blocks_paragraph_path_idx').on(columns._path), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [realizations.id],
      name: 'realizations_blocks_paragraph_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const realizations_blocks_gallery_images = pgTable('realizations_blocks_gallery_images', {
  _order: integer('_order').notNull(),
  _parentID: varchar('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  image: integer('image_id').notNull().references(() => media.id, {
      onDelete: 'set null'
  }),
}, (columns) => [
    index('realizations_blocks_gallery_images_order_idx').on(columns._order), index('realizations_blocks_gallery_images_parent_id_idx').on(columns._parentID), index('realizations_blocks_gallery_images_image_idx').on(columns.image), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [realizations_blocks_gallery.id],
      name: 'realizations_blocks_gallery_images_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const realizations_blocks_gallery = pgTable('realizations_blocks_gallery', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  _path: text('_path').notNull(),
  id: varchar('id').primaryKey(),
  layout: enum_realizations_blocks_gallery_layout('layout').default("grid"),
  blockName: varchar('block_name'),
}, (columns) => [
    index('realizations_blocks_gallery_order_idx').on(columns._order), index('realizations_blocks_gallery_parent_id_idx').on(columns._parentID), index('realizations_blocks_gallery_path_idx').on(columns._path), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [realizations.id],
      name: 'realizations_blocks_gallery_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const realizations_blocks_quote = pgTable('realizations_blocks_quote', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  _path: text('_path').notNull(),
  id: varchar('id').primaryKey(),
  content: varchar('content').notNull(),
  author: varchar('author').notNull(),
  authorContext: varchar('author_context'),
  blockName: varchar('block_name'),
}, (columns) => [
    index('realizations_blocks_quote_order_idx').on(columns._order), index('realizations_blocks_quote_parent_id_idx').on(columns._parentID), index('realizations_blocks_quote_path_idx').on(columns._path), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [realizations.id],
      name: 'realizations_blocks_quote_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const realizations_blocks_before_after = pgTable('realizations_blocks_before_after', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  _path: text('_path').notNull(),
  id: varchar('id').primaryKey(),
  before: integer('before_id').notNull().references(() => media.id, {
      onDelete: 'set null'
  }),
  after: integer('after_id').notNull().references(() => media.id, {
      onDelete: 'set null'
  }),
  caption: varchar('caption'),
  blockName: varchar('block_name'),
}, (columns) => [
    index('realizations_blocks_before_after_order_idx').on(columns._order), index('realizations_blocks_before_after_parent_id_idx').on(columns._parentID), index('realizations_blocks_before_after_path_idx').on(columns._path), index('realizations_blocks_before_after_before_idx').on(columns.before), index('realizations_blocks_before_after_after_idx').on(columns.after), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [realizations.id],
      name: 'realizations_blocks_before_after_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const realizations = pgTable('realizations', {
  id: serial('id').primaryKey(),
  title: varchar('title').notNull(),
  slug: varchar('slug'),
  category: enum_realizations_category('category').notNull().default("haircut"),
  shortDescription: varchar('short_description').notNull(),
  coverImage: integer('cover_image_id').notNull().references(() => media.id, {
      onDelete: 'set null'
  }),
  metaTitle: varchar('meta_title'),
  metaDescription: varchar('meta_description'),
  ogImage: integer('og_image_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  publishedAt: timestamp('published_at', {mode: 'string',withTimezone: true,precision: 3}).notNull(),
  isFeatured: boolean('is_featured').default(false),
  isActive: boolean('is_active').default(true),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    uniqueIndex('realizations_slug_idx').on(columns.slug), index('realizations_cover_image_idx').on(columns.coverImage), index('realizations_og_image_idx').on(columns.ogImage), index('realizations_updated_at_idx').on(columns.updatedAt), index('realizations_created_at_idx').on(columns.createdAt),
]
)


export const payload_kv = pgTable('payload_kv', {
  id: serial('id').primaryKey(),
  key: varchar('key').notNull(),
  data: jsonb('data').notNull(),
}, (columns) => [
    uniqueIndex('payload_kv_key_idx').on(columns.key),
]
)


export const payload_locked_documents = pgTable('payload_locked_documents', {
  id: serial('id').primaryKey(),
  globalSlug: varchar('global_slug'),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug), index('payload_locked_documents_updated_at_idx').on(columns.updatedAt), index('payload_locked_documents_created_at_idx').on(columns.createdAt),
]
)


export const payload_locked_documents_rels = pgTable('payload_locked_documents_rels', {
  id: serial('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: varchar('path').notNull(),
  usersID: integer('users_id'),
  mediaID: integer('media_id'),
  servicesID: integer('services_id'),
  testimonialsID: integer('testimonials_id'),
  realizationsID: integer('realizations_id'),
}, (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order), index('payload_locked_documents_rels_parent_idx').on(columns.parent), index('payload_locked_documents_rels_path_idx').on(columns.path), index('payload_locked_documents_rels_users_id_idx').on(columns.usersID), index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID), index('payload_locked_documents_rels_services_id_idx').on(columns.servicesID), index('payload_locked_documents_rels_testimonials_id_idx').on(columns.testimonialsID), index('payload_locked_documents_rels_realizations_id_idx').on(columns.realizationsID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['servicesID']],
      foreignColumns: [services.id],
      name: 'payload_locked_documents_rels_services_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['testimonialsID']],
      foreignColumns: [testimonials.id],
      name: 'payload_locked_documents_rels_testimonials_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['realizationsID']],
      foreignColumns: [realizations.id],
      name: 'payload_locked_documents_rels_realizations_fk'
    }).onDelete('cascade'),
]
)


export const payload_preferences = pgTable('payload_preferences', {
  id: serial('id').primaryKey(),
  key: varchar('key'),
  value: jsonb('value'),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('payload_preferences_key_idx').on(columns.key), index('payload_preferences_updated_at_idx').on(columns.updatedAt), index('payload_preferences_created_at_idx').on(columns.createdAt),
]
)


export const payload_preferences_rels = pgTable('payload_preferences_rels', {
  id: serial('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: varchar('path').notNull(),
  usersID: integer('users_id'),
}, (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order), index('payload_preferences_rels_parent_idx').on(columns.parent), index('payload_preferences_rels_path_idx').on(columns.path), index('payload_preferences_rels_users_id_idx').on(columns.usersID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk'
    }).onDelete('cascade'),
]
)


export const payload_migrations = pgTable('payload_migrations', {
  id: serial('id').primaryKey(),
  name: varchar('name'),
  batch: numeric('batch', {mode: 'number'}),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}).defaultNow().notNull(),
}, (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt), index('payload_migrations_created_at_idx').on(columns.createdAt),
]
)


export const site_settings_nav_links = pgTable('site_settings_nav_links', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  label: varchar('label').notNull(),
  anchor: varchar('anchor').notNull(),
}, (columns) => [
    index('site_settings_nav_links_order_idx').on(columns._order), index('site_settings_nav_links_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_settings.id],
      name: 'site_settings_nav_links_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const site_settings_opening_hours = pgTable('site_settings_opening_hours', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  days: varchar('days').notNull(),
  hours: varchar('hours').notNull(),
}, (columns) => [
    index('site_settings_opening_hours_order_idx').on(columns._order), index('site_settings_opening_hours_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_settings.id],
      name: 'site_settings_opening_hours_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const site_settings_social = pgTable('site_settings_social', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  platform: enum_site_settings_social_platform('platform').notNull(),
  url: varchar('url').notNull(),
}, (columns) => [
    index('site_settings_social_order_idx').on(columns._order), index('site_settings_social_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_settings.id],
      name: 'site_settings_social_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const site_settings_legal_links = pgTable('site_settings_legal_links', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  label: varchar('label').notNull(),
  url: varchar('url').notNull(),
}, (columns) => [
    index('site_settings_legal_links_order_idx').on(columns._order), index('site_settings_legal_links_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_settings.id],
      name: 'site_settings_legal_links_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const site_settings = pgTable('site_settings', {
  id: serial('id').primaryKey(),
  logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  brandText: varchar('brand_text').notNull().default("Black Comb"),
  address_street: varchar('address_street').notNull(),
  address_postalCode: varchar('address_postal_code').notNull(),
  address_city: varchar('address_city').notNull(),
  coordinates_lat: numeric('coordinates_lat', {mode: 'number'}).notNull(),
  coordinates_lng: numeric('coordinates_lng', {mode: 'number'}).notNull(),
  phone: varchar('phone').notNull(),
  email: varchar('email').notNull(),
  footerTagline: varchar('footer_tagline'),
  copyrightText: varchar('copyright_text').notNull().default("Black Comb. Wszelkie prawa zastrzeżone."),
  showOpeningHoursInFooter: boolean('show_opening_hours_in_footer').default(true),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}),
}, (columns) => [
    index('site_settings_logo_idx').on(columns.logo),
]
)


export const homepage_keywords_banner_keywords = pgTable('homepage_keywords_banner_keywords', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  text: varchar('text'),
}, (columns) => [
    index('homepage_keywords_banner_keywords_order_idx').on(columns._order), index('homepage_keywords_banner_keywords_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepage.id],
      name: 'homepage_keywords_banner_keywords_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const homepage_about_section_stats = pgTable('homepage_about_section_stats', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: varchar('id').primaryKey(),
  value: varchar('value').notNull(),
  label: varchar('label').notNull(),
}, (columns) => [
    index('homepage_about_section_stats_order_idx').on(columns._order), index('homepage_about_section_stats_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepage.id],
      name: 'homepage_about_section_stats_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const homepage = pgTable('homepage', {
  id: serial('id').primaryKey(),
  heroSection_title: varchar('hero_section_title').notNull(),
  heroSection_subtitle: varchar('hero_section_subtitle'),
  heroSection_backgroundImage: integer('hero_section_background_image_id').notNull().references(() => media.id, {
      onDelete: 'set null'
  }),
  heroSection_cta_label: varchar('hero_section_cta_label'),
  heroSection_cta_anchor: varchar('hero_section_cta_anchor'),
  keywordsBanner_isEnabled: boolean('keywords_banner_is_enabled').default(true),
  aboutSection_isEnabled: boolean('about_section_is_enabled').default(true),
  aboutSection_eyebrow: varchar('about_section_eyebrow'),
  aboutSection_title: varchar('about_section_title').notNull(),
  aboutSection_description: jsonb('about_section_description').notNull(),
  aboutSection_image: integer('about_section_image_id').notNull().references(() => media.id, {
      onDelete: 'set null'
  }),
  servicesSection_isEnabled: boolean('services_section_is_enabled').default(true),
  servicesSection_eyebrow: varchar('services_section_eyebrow'),
  servicesSection_title: varchar('services_section_title').notNull().default("Usługi"),
  servicesSection_description: varchar('services_section_description'),
  realizationsSection_isEnabled: boolean('realizations_section_is_enabled').default(true),
  realizationsSection_eyebrow: varchar('realizations_section_eyebrow'),
  realizationsSection_title: varchar('realizations_section_title').notNull().default("Realizacje"),
  realizationsSection_description: varchar('realizations_section_description'),
  realizationsSection_displayLimit: numeric('realizations_section_display_limit', {mode: 'number'}).default(4),
  realizationsSection_ctaLabel: varchar('realizations_section_cta_label').default("Zobacz wszystkie realizacje"),
  testimonialsSection_isEnabled: boolean('testimonials_section_is_enabled').default(true),
  testimonialsSection_eyebrow: varchar('testimonials_section_eyebrow'),
  testimonialsSection_title: varchar('testimonials_section_title').notNull().default("Opinie klientów"),
  testimonialsSection_description: varchar('testimonials_section_description'),
  contactSection_isEnabled: boolean('contact_section_is_enabled').default(true),
  contactSection_eyebrow: varchar('contact_section_eyebrow'),
  contactSection_title: varchar('contact_section_title').notNull().default("Kontakt"),
  contactSection_description: varchar('contact_section_description'),
  contactSection_formCtaLabel: varchar('contact_section_form_cta_label').notNull().default("Wyślij wiadomość"),
  contactSection_mapZoom: numeric('contact_section_map_zoom', {mode: 'number'}).default(15),
  updatedAt: timestamp('updated_at', {mode: 'string',withTimezone: true,precision: 3}),
  createdAt: timestamp('created_at', {mode: 'string',withTimezone: true,precision: 3}),
}, (columns) => [
    index('homepage_hero_section_hero_section_background_image_idx').on(columns.heroSection_backgroundImage), index('homepage_about_section_about_section_image_idx').on(columns.aboutSection_image),
]
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
    }),
      }))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
            relationName: 'sessions',
    }),
      }))
export const relations_media = relations(media, () => ({
  
      }))
export const relations_services = relations(services, ({ one }) => ({
  image: one(media, {
    
    fields: [services.image],
    references: [media.id],
    relationName: 'image',
    }),
      }))
export const relations_testimonials = relations(testimonials, ({ one }) => ({
  authorAvatar: one(media, {
    
    fields: [testimonials.authorAvatar],
    references: [media.id],
    relationName: 'authorAvatar',
    }),
      }))
export const relations_realizations_gallery = relations(realizations_gallery, ({ one }) => ({
  _parentID: one(realizations, {
    
    fields: [realizations_gallery._parentID],
    references: [realizations.id],
    relationName: 'gallery',
    }),
    image: one(media, {
    
    fields: [realizations_gallery.image],
    references: [media.id],
    relationName: 'image',
    }),
      }))
export const relations_realizations_blocks_paragraph = relations(realizations_blocks_paragraph, ({ one }) => ({
  _parentID: one(realizations, {
    
    fields: [realizations_blocks_paragraph._parentID],
    references: [realizations.id],
    relationName: '_blocks_paragraph',
    }),
      }))
export const relations_realizations_blocks_gallery_images = relations(realizations_blocks_gallery_images, ({ one }) => ({
  _parentID: one(realizations_blocks_gallery, {
    
    fields: [realizations_blocks_gallery_images._parentID],
    references: [realizations_blocks_gallery.id],
    relationName: 'images',
    }),
    image: one(media, {
    
    fields: [realizations_blocks_gallery_images.image],
    references: [media.id],
    relationName: 'image',
    }),
      }))
export const relations_realizations_blocks_gallery = relations(realizations_blocks_gallery, ({ one, many }) => ({
  _parentID: one(realizations, {
    
    fields: [realizations_blocks_gallery._parentID],
    references: [realizations.id],
    relationName: '_blocks_gallery',
    }),
    images: many(realizations_blocks_gallery_images, {
            relationName: 'images',
    }),
      }))
export const relations_realizations_blocks_quote = relations(realizations_blocks_quote, ({ one }) => ({
  _parentID: one(realizations, {
    
    fields: [realizations_blocks_quote._parentID],
    references: [realizations.id],
    relationName: '_blocks_quote',
    }),
      }))
export const relations_realizations_blocks_before_after = relations(realizations_blocks_before_after, ({ one }) => ({
  _parentID: one(realizations, {
    
    fields: [realizations_blocks_before_after._parentID],
    references: [realizations.id],
    relationName: '_blocks_beforeAfter',
    }),
    before: one(media, {
    
    fields: [realizations_blocks_before_after.before],
    references: [media.id],
    relationName: 'before',
    }),
    after: one(media, {
    
    fields: [realizations_blocks_before_after.after],
    references: [media.id],
    relationName: 'after',
    }),
      }))
export const relations_realizations = relations(realizations, ({ one, many }) => ({
  coverImage: one(media, {
    
    fields: [realizations.coverImage],
    references: [media.id],
    relationName: 'coverImage',
    }),
    gallery: many(realizations_gallery, {
            relationName: 'gallery',
    }),
    _blocks_paragraph: many(realizations_blocks_paragraph, {
            relationName: '_blocks_paragraph',
    }),
    _blocks_gallery: many(realizations_blocks_gallery, {
            relationName: '_blocks_gallery',
    }),
    _blocks_quote: many(realizations_blocks_quote, {
            relationName: '_blocks_quote',
    }),
    _blocks_beforeAfter: many(realizations_blocks_before_after, {
            relationName: '_blocks_beforeAfter',
    }),
    ogImage: one(media, {
    
    fields: [realizations.ogImage],
    references: [media.id],
    relationName: 'ogImage',
    }),
      }))
export const relations_payload_kv = relations(payload_kv, () => ({
  
      }))
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
  parent: one(payload_locked_documents, {
    
    fields: [payload_locked_documents_rels.parent],
    references: [payload_locked_documents.id],
    relationName: '_rels',
    }),
    usersID: one(users, {
    
    fields: [payload_locked_documents_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
    mediaID: one(media, {
    
    fields: [payload_locked_documents_rels.mediaID],
    references: [media.id],
    relationName: 'media',
    }),
    servicesID: one(services, {
    
    fields: [payload_locked_documents_rels.servicesID],
    references: [services.id],
    relationName: 'services',
    }),
    testimonialsID: one(testimonials, {
    
    fields: [payload_locked_documents_rels.testimonialsID],
    references: [testimonials.id],
    relationName: 'testimonials',
    }),
    realizationsID: one(realizations, {
    
    fields: [payload_locked_documents_rels.realizationsID],
    references: [realizations.id],
    relationName: 'realizations',
    }),
      }))
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
  _rels: many(payload_locked_documents_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
  parent: one(payload_preferences, {
    
    fields: [payload_preferences_rels.parent],
    references: [payload_preferences.id],
    relationName: '_rels',
    }),
    usersID: one(users, {
    
    fields: [payload_preferences_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
      }))
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_migrations = relations(payload_migrations, () => ({
  
      }))
export const relations_site_settings_nav_links = relations(site_settings_nav_links, ({ one }) => ({
  _parentID: one(site_settings, {
    
    fields: [site_settings_nav_links._parentID],
    references: [site_settings.id],
    relationName: 'navLinks',
    }),
      }))
export const relations_site_settings_opening_hours = relations(site_settings_opening_hours, ({ one }) => ({
  _parentID: one(site_settings, {
    
    fields: [site_settings_opening_hours._parentID],
    references: [site_settings.id],
    relationName: 'openingHours',
    }),
      }))
export const relations_site_settings_social = relations(site_settings_social, ({ one }) => ({
  _parentID: one(site_settings, {
    
    fields: [site_settings_social._parentID],
    references: [site_settings.id],
    relationName: 'social',
    }),
      }))
export const relations_site_settings_legal_links = relations(site_settings_legal_links, ({ one }) => ({
  _parentID: one(site_settings, {
    
    fields: [site_settings_legal_links._parentID],
    references: [site_settings.id],
    relationName: 'legalLinks',
    }),
      }))
export const relations_site_settings = relations(site_settings, ({ one, many }) => ({
  logo: one(media, {
    
    fields: [site_settings.logo],
    references: [media.id],
    relationName: 'logo',
    }),
    navLinks: many(site_settings_nav_links, {
            relationName: 'navLinks',
    }),
    openingHours: many(site_settings_opening_hours, {
            relationName: 'openingHours',
    }),
    social: many(site_settings_social, {
            relationName: 'social',
    }),
    legalLinks: many(site_settings_legal_links, {
            relationName: 'legalLinks',
    }),
      }))
export const relations_homepage_keywords_banner_keywords = relations(homepage_keywords_banner_keywords, ({ one }) => ({
  _parentID: one(homepage, {
    
    fields: [homepage_keywords_banner_keywords._parentID],
    references: [homepage.id],
    relationName: 'keywordsBanner_keywords',
    }),
      }))
export const relations_homepage_about_section_stats = relations(homepage_about_section_stats, ({ one }) => ({
  _parentID: one(homepage, {
    
    fields: [homepage_about_section_stats._parentID],
    references: [homepage.id],
    relationName: 'aboutSection_stats',
    }),
      }))
export const relations_homepage = relations(homepage, ({ one, many }) => ({
  heroSection_backgroundImage: one(media, {
    
    fields: [homepage.heroSection_backgroundImage],
    references: [media.id],
    relationName: 'heroSection_backgroundImage',
    }),
    keywordsBanner_keywords: many(homepage_keywords_banner_keywords, {
            relationName: 'keywordsBanner_keywords',
    }),
    aboutSection_stats: many(homepage_about_section_stats, {
            relationName: 'aboutSection_stats',
    }),
    aboutSection_image: one(media, {
    
    fields: [homepage.aboutSection_image],
    references: [media.id],
    relationName: 'aboutSection_image',
    }),
      }))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_testimonials_source: typeof enum_testimonials_source
  enum_realizations_blocks_gallery_layout: typeof enum_realizations_blocks_gallery_layout
  enum_realizations_category: typeof enum_realizations_category
  enum_site_settings_social_platform: typeof enum_site_settings_social_platform
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  services: typeof services
  testimonials: typeof testimonials
  realizations_gallery: typeof realizations_gallery
  realizations_blocks_paragraph: typeof realizations_blocks_paragraph
  realizations_blocks_gallery_images: typeof realizations_blocks_gallery_images
  realizations_blocks_gallery: typeof realizations_blocks_gallery
  realizations_blocks_quote: typeof realizations_blocks_quote
  realizations_blocks_before_after: typeof realizations_blocks_before_after
  realizations: typeof realizations
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  site_settings_nav_links: typeof site_settings_nav_links
  site_settings_opening_hours: typeof site_settings_opening_hours
  site_settings_social: typeof site_settings_social
  site_settings_legal_links: typeof site_settings_legal_links
  site_settings: typeof site_settings
  homepage_keywords_banner_keywords: typeof homepage_keywords_banner_keywords
  homepage_about_section_stats: typeof homepage_about_section_stats
  homepage: typeof homepage
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_services: typeof relations_services
  relations_testimonials: typeof relations_testimonials
  relations_realizations_gallery: typeof relations_realizations_gallery
  relations_realizations_blocks_paragraph: typeof relations_realizations_blocks_paragraph
  relations_realizations_blocks_gallery_images: typeof relations_realizations_blocks_gallery_images
  relations_realizations_blocks_gallery: typeof relations_realizations_blocks_gallery
  relations_realizations_blocks_quote: typeof relations_realizations_blocks_quote
  relations_realizations_blocks_before_after: typeof relations_realizations_blocks_before_after
  relations_realizations: typeof relations_realizations
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_site_settings_nav_links: typeof relations_site_settings_nav_links
  relations_site_settings_opening_hours: typeof relations_site_settings_opening_hours
  relations_site_settings_social: typeof relations_site_settings_social
  relations_site_settings_legal_links: typeof relations_site_settings_legal_links
  relations_site_settings: typeof relations_site_settings
  relations_homepage_keywords_banner_keywords: typeof relations_homepage_keywords_banner_keywords
  relations_homepage_about_section_stats: typeof relations_homepage_about_section_stats
  relations_homepage: typeof relations_homepage
}
    

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
    